baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Blog Demo Site"
theme = "anubis2"
disqusShortname = ""

[pagination]
pagerSize = 5

[params.author]
name = "Sivakarthik"
email  = "edu.sivakarthik@gmail.com"
location = "India"

[params]
description = "Trying out this simple minimalist theme for Hugo blog engine."
dateFormat = "2006-01-02"
paginationSinglePost = true


colorTheme = "auto"
colorThemeSwitcher = true

readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
locale = "en-us"
math = false # true: enable mathjax globally (default is false)
toc = true

# Graphcomment support
graphcommentId = ""

GiscusRepo = "Junyi-99/hugo-theme-anubis2"
GiscusRepoId = "R_kgDOLEp76Q"
GiscusCategory = "General"
GiscusCategoryId = "DIC_kwDOLEp76c4CcbPS"
GiscusLazyLoad = false
GiscusDataMapping = "pathname"

# Removed customCSS setting to avoid errors
# customCSS = ["custom-css/custom1.scss", "custom-css/custom2.css"]

social = [
    { id = "github", url = "https://github.com/sivakarthikxo" },
    { id = "linkedin", url = "https://www.linkedin.com/in/sivakarthik-thangaraj/" },
    { id = "email", url = "edu.sivakarthik@gmail.com" }
]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 4

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style              = 'base16-snazzy'
tabWidth           = 4


[params.GoogleAnalytics]
enabled = true
gtag = "G-32F16X8HLF"
